//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package zeroroneof

import (
	context "context"
	fmt "fmt"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	// type Pipeline
	scheme.AddValidationFunc((*Pipeline)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_Pipeline(ctx, op, nil /* fldPath */, obj.(*Pipeline), safe.Cast[*Pipeline](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

var zeroOrOneOfMembershipFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_item_zerorooneof_Pipeline_Tasks_taskStates = validate.NewUnionMembership([2]string{"Tasks[{\"name\": \"succeeded\"}]", ""}, [2]string{"Tasks[{\"name\": \"failed\"}]", ""})

// Validate_Pipeline validates an instance of Pipeline according
// to declarative validation rules in the API schema.
func Validate_Pipeline(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Pipeline) (errs field.ErrorList) {
	// field Pipeline.TypeMeta has no validation

	// field Pipeline.Tasks
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []Task) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// call field-attached validations
			// listType=map requires unique keys
			errs = append(errs, validate.Unique(ctx, op, fldPath, obj, oldObj, func(a Task, b Task) bool { return a.Name == b.Name })...)
			errs = append(errs, validate.ZeroOrOneOfUnion(ctx, op, fldPath, obj, oldObj, zeroOrOneOfMembershipFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_item_zerorooneof_Pipeline_Tasks_taskStates, func(list []Task) bool {
				var matched *Task
				validate.SliceItem(ctx, op, fldPath, list, nil, func(item *Task) bool { return item.Name == "failed" }, validate.DirectEqual, func(ctx context.Context, op operation.Operation, itemPath *field.Path, newItem, oldItem *Task) field.ErrorList {
					matched = newItem
					return nil
				})
				return matched != nil
			}, func(list []Task) bool {
				var matched *Task
				validate.SliceItem(ctx, op, fldPath, list, nil, func(item *Task) bool { return item.Name == "succeeded" }, validate.DirectEqual, func(ctx context.Context, op operation.Operation, itemPath *field.Path, newItem, oldItem *Task) field.ErrorList {
					matched = newItem
					return nil
				})
				return matched != nil
			})...)
			return
		}(fldPath.Child("tasks"), obj.Tasks, safe.Field(oldObj, func(oldObj *Pipeline) []Task { return oldObj.Tasks }))...)

	return errs
}
