//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package typedeftoslice

import (
	context "context"
	fmt "fmt"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	// type Struct
	scheme.AddValidationFunc((*Struct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_Struct(ctx, op, nil /* fldPath */, obj.(*Struct), safe.Cast[*Struct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

// Validate_Min1Type validates an instance of Min1Type according
// to declarative validation rules in the API schema.
func Validate_Min1Type(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj Min1Type) (errs field.ErrorList) {
	earlyReturn := false
	if e := validate.MinItems(ctx, op, fldPath, obj, oldObj, 1); len(e) != 0 {
		errs = append(errs, e...)
		earlyReturn = true
	}
	if earlyReturn {
		return // do not proceed
	}

	return errs
}

// Validate_Min1TypedefType validates an instance of Min1TypedefType according
// to declarative validation rules in the API schema.
func Validate_Min1TypedefType(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj Min1TypedefType) (errs field.ErrorList) {
	earlyReturn := false
	if e := validate.MinItems(ctx, op, fldPath, obj, oldObj, 1); len(e) != 0 {
		errs = append(errs, e...)
		earlyReturn = true
	}
	if earlyReturn {
		return // do not proceed
	}

	return errs
}

// Validate_Min5Type validates an instance of Min5Type according
// to declarative validation rules in the API schema.
func Validate_Min5Type(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj Min5Type) (errs field.ErrorList) {
	earlyReturn := false
	if e := validate.MinItems(ctx, op, fldPath, obj, oldObj, 5); len(e) != 0 {
		errs = append(errs, e...)
		earlyReturn = true
	}
	if earlyReturn {
		return // do not proceed
	}

	return errs
}

// Validate_Min5TypedefType validates an instance of Min5TypedefType according
// to declarative validation rules in the API schema.
func Validate_Min5TypedefType(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj Min5TypedefType) (errs field.ErrorList) {
	earlyReturn := false
	if e := validate.MinItems(ctx, op, fldPath, obj, oldObj, 5); len(e) != 0 {
		errs = append(errs, e...)
		earlyReturn = true
	}
	if earlyReturn {
		return // do not proceed
	}

	return errs
}

// Validate_Struct validates an instance of Struct according
// to declarative validation rules in the API schema.
func Validate_Struct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Struct) (errs field.ErrorList) {
	// field Struct.TypeMeta has no validation
	// field Struct.UnvalidatedField has no validation

	// field Struct.Min1Field
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj Min1Type) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// call the type's validation function
			errs = append(errs, Validate_Min1Type(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("min1Field"), obj.Min1Field, safe.Field(oldObj, func(oldObj *Struct) Min1Type { return oldObj.Min1Field }))...)

	// field Struct.Min5Field
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj Min5Type) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// call the type's validation function
			errs = append(errs, Validate_Min5Type(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("min5Field"), obj.Min5Field, safe.Field(oldObj, func(oldObj *Struct) Min5Type { return oldObj.Min5Field }))...)

	// field Struct.Min1TypedefField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj Min1TypedefType) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// call the type's validation function
			errs = append(errs, Validate_Min1TypedefType(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("min1TypedefField"), obj.Min1TypedefField, safe.Field(oldObj, func(oldObj *Struct) Min1TypedefType { return oldObj.Min1TypedefField }))...)

	// field Struct.Min5TypedefField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj Min5TypedefType) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// call the type's validation function
			errs = append(errs, Validate_Min5TypedefType(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("min5TypedefField"), obj.Min5TypedefField, safe.Field(oldObj, func(oldObj *Struct) Min5TypedefType { return oldObj.Min5TypedefField }))...)

	return errs
}
