//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package bool_key

import (
	context "context"
	fmt "fmt"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*Struct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_Struct(ctx, op, nil /* fldPath */, obj.(*Struct), safe.Cast[*Struct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	scheme.AddValidationFunc((*StructWithTypedef)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_StructWithTypedef(ctx, op, nil /* fldPath */, obj.(*StructWithTypedef), safe.Cast[*StructWithTypedef](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

func Validate_Struct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Struct) (errs field.ErrorList) {
	// field Struct.TypeMeta has no validation

	// field Struct.ListField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []Item) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.SliceItem(ctx, op, fldPath, obj, oldObj, func(item *Item) bool { return item.BoolKey == true }, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Item) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "item ListField[boolKey=true]")
			})...)
			errs = append(errs, validate.Unique(ctx, op, fldPath, obj, oldObj, func(a Item, b Item) bool { return a.BoolKey == b.BoolKey })...)
			return
		}(fldPath.Child("listField"), obj.ListField, safe.Field(oldObj, func(oldObj *Struct) []Item { return oldObj.ListField }))...)

	// field Struct.MultiKey
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []MultiKeyItem) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.SliceItem(ctx, op, fldPath, obj, oldObj, func(item *MultiKeyItem) bool { return item.Key1 == true && item.Key2 == 5 && item.Key3 == "x" }, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *MultiKeyItem) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "item MultiKey[key1=true,key2=5,key3=x]")
			})...)
			errs = append(errs, validate.Unique(ctx, op, fldPath, obj, oldObj, func(a MultiKeyItem, b MultiKeyItem) bool {
				return a.Key1 == b.Key1 && a.Key2 == b.Key2 && a.Key3 == b.Key3
			})...)
			return
		}(fldPath.Child("multiKey"), obj.MultiKey, safe.Field(oldObj, func(oldObj *Struct) []MultiKeyItem { return oldObj.MultiKey }))...)

	return errs
}

func Validate_StructWithTypedef(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *StructWithTypedef) (errs field.ErrorList) {
	// field StructWithTypedef.TypeMeta has no validation

	// field StructWithTypedef.TypedefField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj TypedefList) (errs field.ErrorList) {
			errs = append(errs, Validate_TypedefList(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("typedefField"), obj.TypedefField, safe.Field(oldObj, func(oldObj *StructWithTypedef) TypedefList { return oldObj.TypedefField }))...)

	return errs
}

func Validate_TypedefList(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj TypedefList) (errs field.ErrorList) {
	// type TypedefList
	if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
		return nil // no changes
	}
	errs = append(errs, validate.SliceItem(ctx, op, fldPath, obj, oldObj, func(item *TypedefItem) bool { return item.BoolField == true }, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *TypedefItem) field.ErrorList {
		return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "item TypedefList[boolField=true]")
	})...)
	errs = append(errs, validate.Unique(ctx, op, fldPath, obj, oldObj, func(a TypedefItem, b TypedefItem) bool { return a.BoolField == b.BoolField })...)

	return errs
}
