//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package union

import (
	context "context"
	fmt "fmt"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*Pipeline)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_Pipeline(ctx, op, nil /* fldPath */, obj.(*Pipeline), safe.Cast[*Pipeline](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

var unionMembershipForPipelinetaskStates = validate.NewUnionMembership([2]string{"Tasks[name=\"succeeded\"]", "Tasks[name=\"succeeded\"]"}, [2]string{"Tasks[name=\"failed\"]", "Tasks[name=\"failed\"]"}, [2]string{"Tasks[name=\"running\"]", "Tasks[name=\"running\"]"}, [2]string{"Tasks[name=\"pending\"]", "Tasks[name=\"pending\"]"})

func Validate_Pipeline(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Pipeline) (errs field.ErrorList) {
	// type Pipeline
	if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
		return nil // no changes
	}
	errs = append(errs, validate.Union(ctx, op, fldPath, obj, oldObj, unionMembershipForPipelinetaskStates, func(obj *Pipeline) any {
		return func() interface{} {
			if obj != nil && obj.Tasks != nil {
				for _, item := range obj.Tasks {
					if item.Name == "succeeded" {
						return true
					}
				}
			}
			return false
		}()
	}, func(obj *Pipeline) any {
		return func() interface{} {
			if obj != nil && obj.Tasks != nil {
				for _, item := range obj.Tasks {
					if item.Name == "failed" {
						return true
					}
				}
			}
			return false
		}()
	}, func(obj *Pipeline) any {
		return func() interface{} {
			if obj != nil && obj.Tasks != nil {
				for _, item := range obj.Tasks {
					if item.Name == "running" {
						return true
					}
				}
			}
			return false
		}()
	}, func(obj *Pipeline) any {
		return func() interface{} {
			if obj != nil && obj.Tasks != nil {
				for _, item := range obj.Tasks {
					if item.Name == "pending" {
						return true
					}
				}
			}
			return false
		}()
	})...)

	// field Pipeline.TypeMeta has no validation
	// field Pipeline.Tasks has no validation
	return errs
}
