//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package eqoneofstring

import (
	context "context"
	fmt "fmt"

	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*Struct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_Struct(ctx, op, nil /* fldPath */, obj.(*Struct), safe.Cast[*Struct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

func Validate_Struct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Struct) (errs field.ErrorList) {
	// field Struct.TypeMeta has no validation

	// field Struct.StringField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			errs = append(errs, validate.EqOneOf(ctx, op, fldPath, obj, oldObj, []string{"valid1", "valid2", "valid3"})...)
			return
		}(fldPath.Child("stringField"), &obj.StringField, safe.Field(oldObj, func(oldObj *Struct) *string { return &oldObj.StringField }))...)

	// field Struct.StringPtrField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			errs = append(errs, validate.EqOneOf(ctx, op, fldPath, obj, oldObj, []string{"ptr-valid1", "ptr-valid2"})...)
			return
		}(fldPath.Child("stringPtrField"), obj.StringPtrField, safe.Field(oldObj, func(oldObj *Struct) *string { return oldObj.StringPtrField }))...)

	// field Struct.TypedefStringField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *StringType) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			errs = append(errs, validate.EqOneOf(ctx, op, fldPath, obj, oldObj, []StringType{StringType("typedef-valid1"), StringType("typedef-valid2")})...)
			return
		}(fldPath.Child("typedefStringField"), &obj.TypedefStringField, safe.Field(oldObj, func(oldObj *Struct) *StringType { return &oldObj.TypedefStringField }))...)

	// field Struct.TypedefStringPtrField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *StringType) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			errs = append(errs, validate.EqOneOf(ctx, op, fldPath, obj, oldObj, []StringType{StringType("ptr-typedef-valid1"), StringType("ptr-typedef-valid2")})...)
			return
		}(fldPath.Child("typedefStringPtrField"), obj.TypedefStringPtrField, safe.Field(oldObj, func(oldObj *Struct) *StringType { return oldObj.TypedefStringPtrField }))...)

	// field Struct.StringWithSpacesField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			errs = append(errs, validate.EqOneOf(ctx, op, fldPath, obj, oldObj, []string{"space valid1", "space valid2"})...)
			return
		}(fldPath.Child("stringWithSpacesField"), &obj.StringWithSpacesField, safe.Field(oldObj, func(oldObj *Struct) *string { return &oldObj.StringWithSpacesField }))...)

	// field Struct.ValidatedTypedefField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *ValidatedStringType) (errs field.ErrorList) {
			errs = append(errs, Validate_ValidatedStringType(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("validatedTypedefField"), &obj.ValidatedTypedefField, safe.Field(oldObj, func(oldObj *Struct) *ValidatedStringType { return &oldObj.ValidatedTypedefField }))...)

	return errs
}

func Validate_ValidatedStringType(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ValidatedStringType) (errs field.ErrorList) {
	// type ValidatedStringType
	if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
		return nil // no changes
	}
	errs = append(errs, validate.EqOneOf(ctx, op, fldPath, obj, oldObj, []ValidatedStringType{ValidatedStringType("validated-valid1"), ValidatedStringType("validated-valid2")})...)

	return errs
}
